### ISSUE TITLE
Missing service annotations in service.yaml template file

### ISSUE THREAD

**Issue by mssch** [lightstep/lightstep-microsatellite-helm-chart#9]
While the `service.annotations` is present in the chart `values.yaml` file and in the docs, it is missing from the `templates/service.yaml` file. e.g.
```yaml
apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations: {{ .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
  name: {{ include "lightstep.fullname" . }}
  labels:
    {{- include "lightstep.labels" . | nindent 4 }}
```
Thanks!
